
const event = {
  "id": "2",
  "groupId": null,
  "allDay": null,
  "start": "1",
  "end": "1",
  "daysOfWeek": null,
  "startTime": null,
  "endTime": null,
  "startRecur": null,
  "endRecur": null,
  "title": "titulo",
  "url": null,
  "interactive": null,
  "editable": null,
  "startEditable": null,
  "durationEditable": null,
  "resourceEditable": null,
  "resourceId": null,
  "resourceIds": null,
  "display": null,
  "overlap": null,
  "restriction": null,
  "color": null,
  "backgroundColor": null,
  "borderColor": null,
  "textColor": null,
  "extendedProps": null,

  "state": "reserved", // reserved paid past
}